spring:
  application:
    name: The-Last-Supper

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: ${SQL_INIT_MODE:never}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: ${JPA_DDI:false}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jwt:
    secret: ${SECRET_KEY}

  config:
    import: optional:file:.env[.properties]
